defmodule SignatureH12GoldenFixtureTest do
  @moduledoc """
  H12 SS4: the committed upstream golden
  (`test/fixtures/upstream_h12_parse_value_3_4_0.json`, generated by
  `plan/research/upstream_golden/gen_h12_golden.py` from dspy 3.4.0
  `parse_value(s, float)` / `parse_value(s, int)`) is consumed here at the
  public entry point.

  Every non-deviation row is pinned: our verdict must equal upstream's.
  Deviation rows (Horst rulings 2026-09-29, corrupt-or-lose principle) are
  pinned as REJECT: `"NaN"/"nan"/"NAN"/"inf"/"-inf"/"INF"/"+inf"` and
  `"true"/"True"/"False"` — upstream accepts these (its judge clamp would
  turn NaN into a perfect 1.0; pydantic coerces boolean words to numbers),
  we reject them, and the rejection is declared in docs/COMPATIBILITY.md.

  M1-b lesson applied: a generated fixture can silently record an error as an
  expected value, so every row is asserted to be of the type it claims.
  """
  use ExUnit.Case, async: true

  @fixture Path.expand("fixtures/upstream_h12_parse_value_3_4_0.json", __DIR__)
  @fixture_data Jason.decode!(File.read!(@fixture))
  @rows @fixture_data["cases"]

  # Horst rulings 2026-09-29: inputs we REJECT although upstream accepts them.
  @deviation_inputs ~w(NaN nan NAN inf -inf INF +inf true True False)

  defmodule NumLM do
    @behaviour Dspy.LM
    defstruct [:answer]

    @impl true
    def generate(%__MODULE__{answer: a}, _request) do
      {:ok,
       %{
         choices: [%{message: %{role: "assistant", content: "Answer: #{a}"}}],
         finish_reason: "stop",
         usage: nil
       }}
    end

    @impl true
    def supports?(_lm, _f), do: true
  end

  defmodule IntLM do
    @behaviour Dspy.LM
    defstruct [:count]

    @impl true
    def generate(%__MODULE__{count: c}, _request) do
      {:ok,
       %{
         choices: [%{message: %{role: "assistant", content: "Count: #{c}"}}],
         finish_reason: "stop",
         usage: nil
       }}
    end

    @impl true
    def supports?(_lm, _f), do: true
  end

  defmodule NumSig do
    use Dspy.Signature
    input_field(:question, :string, "q")
    output_field(:answer, :number, "n")
  end

  defmodule IntSig do
    use Dspy.Signature
    input_field(:question, :string, "q")
    output_field(:count, :integer, "i")
  end

  defp call_num(s) do
    p = Dspy.Predict.new(NumSig, max_retries: 0, max_output_retries: 0)
    Dspy.context([lm: %NumLM{answer: s}], fn -> Dspy.call(p, %{question: "q"}) end)
  end

  defp call_int(s) do
    p = Dspy.Predict.new(IntSig, max_retries: 0, max_output_retries: 0)
    Dspy.context([lm: %IntLM{count: s}], fn -> Dspy.call(p, %{question: "q"}) end)
  end

  # Exact IEEE-754 decode of Python's `float.hex()` format (the golden's
  # value_hex encoding): [-]0x[hexdigits][.hexdigits][pN].
  # The leading "1" after 0x is the implicit (normalized) bit — value = 1.f * 2^p.
  defp float_from_hex(hex) do
    {sign, rest} =
      if String.starts_with?(hex, "-"), do: {-1.0, String.slice(hex, 1..-1//1)}, else: {1.0, hex}

    [mantissa_hex, exp_str] = String.split(rest, "p")
    exp = String.to_integer(exp_str)

    # mantissa_hex looks like "0x1.999999999999a" or "0x1p+0" or "0x0p+0" —
    # strip the "0x", split on "."; value = mantissa_int * 2^p.
    # (For normalized floats the mantissa is 1.frac; for 0.0 it is just 0.)
    mantissa_no_x = String.replace_prefix(mantissa_hex, "0x", "")

    [int_part, frac_part] =
      case String.split(mantissa_no_x, ".") do
        [a, b] -> [a, b]
        [a] -> [a, ""]
      end

    frac_hex = frac_part

    significand =
      frac_hex
      |> String.graphemes()
      |> Enum.with_index()
      |> Enum.reduce(String.to_integer(int_part, 16), fn {ch, i}, acc ->
        acc + hex_digit_value(ch) * :math.pow(16, -1 - i)
      end)

    sign * :math.pow(2, exp) * significand
  end

  defp hex_digit_value(c) when c in ~w(0 1 2 3 4 5 6 7 8 9), do: String.to_integer(c)
  defp hex_digit_value(c) when c in ~w(a b c d e f), do: String.to_integer(c, 16)
  defp hex_digit_value(c) when c in ~w(A B C D E F), do: String.to_integer(c, 16)

  test "fixture is well-formed: every row has an explicit verdict of a claimed type" do
    assert length(@rows) > 100, "golden fixture unexpectedly small"

    for row <- @rows do
      upstream = row["upstream"]
      assert is_boolean(upstream["raises"]), "row #{inspect(row)}: missing explicit raises flag"
      assert upstream["type"] in ["float", "int"], "row #{inspect(row)}: bad type"

      if upstream["raises"] do
        assert is_binary(upstream["error_type"]),
               "row #{inspect(row)}: raise row must name the upstream error type"
      else
        assert Map.has_key?(upstream, "value") or Map.has_key?(upstream, "value_hex") or
                 Map.has_key?(upstream, "value_marker"),
               "row #{inspect(row)}: accept row must carry a value"
      end
    end
  end

  test "every deviation row is marked and rejected by us (Horst rulings)" do
    # Upstream rejects NaN/inf for int (so those int rows are NOT deviations);
    # for float, upstream accepts them (its judge clamp) — we deviate and reject.
    for row <- @rows,
        row["input"] in @deviation_inputs,
        row["upstream"]["raises"] == false do
      upstream = row["upstream"]

      # The golden records the upstream-accepted verdict:
      #  - value_hex (float): a representable number ("true" -> 1.0, "False" -> 0.0);
      #  - value (int): a representable integer ("true" -> 1, "False" -> 0);
      #  - value_marker (float): NaN/inf — not representable in BEAM, never a value we would ever return.
      assert Map.has_key?(upstream, "value_hex") or Map.has_key?(upstream, "value_marker") or
               Map.has_key?(upstream, "value"),
             "deviation row #{inspect(row["input"])} must carry the upstream-accepted value (hex/marker/int) or a marker"

      assert row["declared_deviation"] == true,
             "upstream accepts #{inspect(row["input"])} — the deviation must be marked"

      case row["annotation"] do
        "float" ->
          assert {:error,
                  {:output_parse_failed, {:invalid_output_value, :answer, :invalid_number}, _}} =
                   call_num(row["input"])

        "int" ->
          assert {:error,
                  {:output_parse_failed, {:invalid_output_value, :count, :invalid_integer}, _}} =
                   call_int(row["input"])
      end
    end
  end

  test "non-deviation float rows: our verdict equals upstream's" do
    for row <- @rows,
        row["annotation"] == "float",
        row["input"] not in @deviation_inputs do
      upstream = row["upstream"]

      if upstream["raises"] do
        assert {:error,
                {:output_parse_failed, {:invalid_output_value, :answer, :invalid_number}, _}} =
                 call_num(row["input"]),
               "float #{inspect(row["input"])}: upstream rejects (#{upstream["error_type"]}) but we accepted"
      else
        expected =
          case upstream do
            %{"value_hex" => hex} -> float_from_hex(hex)
            %{"value" => v} -> v
            _ -> flunk("float #{inspect(row["input"])}: no value in golden row")
          end

        assert {:ok, %Dspy.Prediction{attrs: %{answer: got}}} = call_num(row["input"]),
               "float #{inspect(row["input"])}: upstream accepts #{inspect(expected)} but we rejected"

        assert got == expected and is_float(got),
               "float #{inspect(row["input"])}: got #{inspect(got)}, upstream #{inspect(expected)}"
      end
    end
  end

  test "non-deviation int rows: our verdict equals upstream's" do
    for row <- @rows,
        row["annotation"] == "int",
        row["input"] not in @deviation_inputs do
      upstream = row["upstream"]

      if upstream["raises"] do
        assert {:error,
                {:output_parse_failed, {:invalid_output_value, :count, :invalid_integer}, _}} =
                 call_int(row["input"]),
               "int #{inspect(row["input"])}: upstream rejects (#{upstream["error_type"]}) but we accepted"
      else
        expected =
          case upstream do
            %{"value" => v} -> v
            _ -> flunk("int #{inspect(row["input"])}: no value in golden row")
          end

        assert {:ok, %Dspy.Prediction{attrs: %{count: got}}} = call_int(row["input"]),
               "int #{inspect(row["input"])}: upstream accepts #{inspect(expected)} but we rejected"

        assert got == expected and is_integer(got),
               "int #{inspect(row["input"])}: got #{inspect(got)}, upstream #{inspect(expected)}"
      end
    end
  end
end
