name: Feature request
description: Propose an improvement or new capability
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature.

        This repo ships in small, proven slices. The most actionable requests include:
        - a concrete user workflow
        - how to test it deterministically (offline)
        - any upstream DSPy references

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What are you trying to accomplish?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: proof
    attributes:
      label: Proof artifact idea
      description: What deterministic test or offline example could prove this works?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to upstream DSPy docs/code, or relevant examples.
    validations:
      required: false
