#!/usr/bin/env python3
"""M1-e phase 1 golden fixture generator: CPython `random` ONLY.

Produces `test/fixtures/upstream_m1e_random_3_4_0.json` from REAL CPython
(`python3`'s `random` module). Every value in the fixture is computed here;
nothing is transcribed by hand or generated by Elixir. If Elixir disagrees
with the fixture, Elixir is wrong.

Coverage (contract rows, `openspec/changes/m1e-dataset-dataloader/`):
  row 1: first 5 x 32-bit words of `random.Random(seed)` for the contract seeds
         0, 1, 42, 2023, 2**32, 2**64+3, -5
  row 2: `shuffle` of list(range(n)) for n in {0, 1, 2, 10, 100, 1000}, seed 0
  row 3: `sample(range(n), k, seed)` pool branch, set branch, and the
         k = 6 setsize boundary; plus the spec scenarios
         sample(0..9, 3, seed 0) and sample(0..99, 3, seed 0)
  randrange (handoff: randrange vectors for the contract seeds)

Re-running and diffing against the committed fixture is part of review
(contract row 31 / R6).

Usage: python3 plan/research/upstream_golden/gen_m1e_random_golden.py
Writes: test/fixtures/upstream_m1e_random_3_4_0.json
"""

import datetime
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "test" / "fixtures" / "upstream_m1e_random_3_4_0.json"

# Contract seeds (row 1): 0, 1, 42, 2023, 2**32, 2**64+3, -5.
SEEDS = [0, 1, 42, 2023, 2**32, 2**64 + 3, -5]

# Contract shuffle sizes (row 2): 0, 1, 2, 10, 100, 1000.
SHUFFLE_NS = [0, 1, 2, 10, 100, 1000]


def first5(seed):
    r = random.Random(seed)
    return [r.getrandbits(32) for _ in range(5)]


def shuffled(seed, n):
    xs = list(range(n))
    random.Random(seed).shuffle(xs)
    return xs


def sampled(seed, n, k):
    return random.Random(seed).sample(range(n), k)


def randranged(seed, n):
    return random.Random(seed).randrange(n)


def main():
    fixture = {
        "_meta": {
            "source": "CPython %s (random module)" % sys.version.split()[0],
            "python": sys.version,
            "generated": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "description": (
                "M1-e phase 1 golden: CPython MT19937 vectors for Dspy.Random. "
                "Every value computed by CPython `random` at generation time; "
                "see gen_m1e_random_golden.py."
            ),
        },
        "first5": {str(seed): first5(seed) for seed in SEEDS},
        # abs(seed) parity pin: -5 must equal 5 (CPython seeds with abs(seed)).
        "abs_seed_parity": {str(seed): first5(seed) for seed in (-5, 5)},
        "shuffle": {str(n): shuffled(0, n) for n in SHUFFLE_NS},
        "sample": {
            # spec scenarios (both named in the spec).
            "n10_k3_seed0": sampled(0, 10, 3),
            "n100_k3_seed0": sampled(0, 100, 3),
            # pool branch (n small relative to k: setsize formula not engaged).
            "n10_k3_seed42": sampled(42, 10, 3),
            "n5_k3_seed7": sampled(7, 5, 3),
            # k = 6 setsize boundary: CPython's sample uses the pool branch
            # while n <= setsize, where for k > 5 setsize = 21 + 4**ceil(log(3k, 4)) = 85;
            # the set branch takes over at n > 85. n = 20 and n = 21 pin the
            # pool branch (the n > 85 vector is n100_k3_seed42).
            "n20_k6_seed0": sampled(0, 20, 6),
            "n21_k6_seed0": sampled(0, 21, 6),
            # Boundary-divergence pins (verified 2026-10-06): cases where the
            # pool and set branches GENUINELY DISAGREE for the same seed, on
            # both sides of the setsize boundary. For k <= 5 setsize = 21,
            # so n = 21 is the last pool-branch size and n = 22 the first
            # set-branch size; for k = 6, setsize = 85, so n = 85 is the
            # last pool-branch size and n = 86 the first set-branch size.
            # These kill the off-by-one branch-condition mutation
            # (n < setsize instead of n <=).
            "n85_k6_seed5": sampled(5, 85, 6),
            "n21_k5_seed2": sampled(2, 21, 5),
            "n22_k5_seed2": sampled(2, 22, 5),
            "n86_k6_seed5": sampled(5, 86, 6),
            # set branch (n large relative to k).
            "n100_k3_seed42": sampled(42, 100, 3),
            "n1000_k6_seed0": sampled(0, 1000, 6),
            # Divergence pin: n > setsize where pool and set branches give
            # DIFFERENT results (verified 2026-10-04). Without this, MG5
            # (always-pool) survives because every other set-branch case
            # happens to agree with the pool branch.
            "n200_k10_seed1": sampled(1, 200, 10),
        },
        "randrange": {
            "n100_seed0": randranged(0, 100),
            "n100_seed1": randranged(1, 100),
            "n10_seed42": randranged(42, 10),
            "n64_seed0": randranged(0, 64),  # power of two: bit_length(64) = 7
            "n65_seed0": randranged(0, 65),  # just past a power of two
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"Wrote {OUT}")
    print(f"  first5 seed 0 = {fixture['first5']['0']}")
    print(f"  shuffle n=10 seed 0 = {fixture['shuffle']['10']}")
    print(f"  sample n=10 k=3 seed 0 = {fixture['sample']['n10_k3_seed0']}")
    print(f"  sample n=100 k=3 seed 0 = {fixture['sample']['n100_k3_seed0']}")


if __name__ == "__main__":
    main()
